[package]
name = "bevy_rapier_benches3d"
version = "0.1.0"
description = "Custom benchmarks for bevy_rapier."
readme = "./README.md"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier3d = { features = ["profiler"], git = "https://github.com/GhostMinerPlus/rapier.git" }
bevy_rapier3d = { version = "0.27", path = "../bevy_rapier3d" }
bevy = { version = "0.15", default-features = false }
