[package]
name = "bevy_rapier_benches3d"
version = "0.1.0"
description = "Custom benchmarks for bevy_rapier."
readme = "./README.md"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
visual = [
    "bevy/x11",
    "bevy/tonemapping_luts",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_pbr",
    "bevy/bevy_gizmos",
    "rapier3d/debug-render",
    #"bevy/bevy_asset",
    "bevy_rapier3d/debug-render-3d",
]

[dependencies]
bevy = { version = "0.14", default-features = false }
rapier3d = { features = ["profiler"], version = "0.22" }
bevy_rapier3d = { version = "0.27", path = "../bevy_rapier3d", default-features = false, features = [
    "dim3",
    "headless",
] }
