[package]
name = "benches_common"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0-rc.3", default-features = false }
bevy_rapier3d = { path = "../bevy_rapier3d", default-features = false }
divan = "0.1"
