[package]
name = "ci"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.2"
bevy_rapier3d = { version = "0.31", path = "../bevy_rapier3d" }
bevy_rapier2d = { version = "0.31", path = "../bevy_rapier2d" }

[[bin]]
name = "ambiguity_detection"
test = false
bench = false
